### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [Luis-aramayo-18/Rolling-Restaurant-Backend#4]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://user-images.githubusercontent.com/53904695/229862828-fd4f6524-f1b0-417d-bb0d-1afa07045437.png)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Luis-aramayo-18** [comment]
Buenas, ya se eliminaron los comentarios, gracias por la informacion !
